In [795]:
import matplotlib as plt
import pandas as pd
import numpy as np
from math import sqrt
from statistics import mean
from numpy import array
import numpy as np

In [798]:
df = pd.read_csv('../data_utf_8/BGCON_CUST_DATA_utf_8_extract.txt', index_col=0)

In [689]:
#df = df.dropna()

df['FP_CAREER'] = df['FP_CAREER'].map(lambda x: 0 if x == 'N' else 1)
df['SIU_CUST_YN'] = df['SIU_CUST_YN'].map(lambda x: 0 if x == 'N' else 1)
df['WEDD_YN'] = df['WEDD_YN'].map(lambda x: 0 if x == 'N' else 1)


df_DIVIDED_SET = df["DIVIDED_SET"] 
df_SEX = df["SEX"]
df_AGE = df["AGE"]
df_RESI_COST = df["RESI_COST"]
df_RESI_TYPE_CODE = df["RESI_TYPE_CODE"]
df_FP_CAREER = df["FP_CAREER"]
df_CUST_RGST = df["CUST_RGST"]
df_CTPR = df["CTPR"]
df_OCCP_GRP_1 = df["OCCP_GRP_1"]
df_OCCP_GRP_2 = df["OCCP_GRP_2"]
df_TOTALPREM = df["TOTALPREM"]
df_MINCRDT = df["MINCRDT"]
df_MAXCRDT = df["MAXCRDT"]
df_WEDD_YN = df["WEDD_YN"]
df_MATE_OCCP_GRP_1 = df["MATE_OCCP_GRP_1"]
df_MATE_OCCP_GRP_2 = df["MATE_OCCP_GRP_2"]
df_CHLD_CNT = df["CHLD_CNT"]
df_LTBN_CHLD_AGE = df["LTBN_CHLD_AGE"]
df_MAX_PAYM_YM = df["MAX_PAYM_YM"]
df_MAX_PRM = df["MAX_PRM"]
df_CUST_INCM = df["CUST_INCM"]
df_RCBASE_HSHD_INCM = df["RCBASE_HSHD_INCM"]
df_JPBASE_HSHD_INCM = df["JPBASE_HSHD_INCM"]


df_SIU_CUST_YN = df["SIU_CUST_YN"]


In [690]:
#for column in range(0, 10):
#    if column not in [6]:
#        df[names[column]] = df[names[column]].astype("category")

In [691]:
df['DIVIDED_SET'].fillna((df['DIVIDED_SET'].mean()), inplace=True)
df['SEX'].fillna((df['SEX'].mean()), inplace=True)
df['AGE'].fillna((df['AGE'].mean()), inplace=True)
df['RESI_COST'].fillna((df['RESI_COST'].mean()), inplace=True)
df['RESI_TYPE_CODE'].fillna((df['RESI_TYPE_CODE'].mean()), inplace=True)
df['FP_CAREER'].fillna((df['FP_CAREER'].mean()), inplace=True)
df['CUST_RGST'].fillna((df['CUST_RGST'].mean()), inplace=True)
df['TOTALPREM'].fillna((df['TOTALPREM'].mean()), inplace=True)
df['MINCRDT'].fillna((df['MINCRDT'].mean()), inplace=True)
df['MAXCRDT'].fillna((df['MAXCRDT'].mean()), inplace=True)
df['CHLD_CNT'].fillna((df['CHLD_CNT'].mean()), inplace=True)
df['LTBN_CHLD_AGE'].fillna((df['LTBN_CHLD_AGE'].mean()), inplace=True)
df['MAX_PAYM_YM'].fillna((df['MAX_PAYM_YM'].mean()), inplace=True)
df['MAX_PRM'].fillna((df['MAX_PRM'].mean()), inplace=True)
df['CUST_INCM'].fillna((df['CUST_INCM'].mean()), inplace=True)
df['RCBASE_HSHD_INCM'].fillna((df['RCBASE_HSHD_INCM'].mean()), inplace=True)
df['JPBASE_HSHD_INCM'].fillna((df['JPBASE_HSHD_INCM'].mean()), inplace=True)

In [692]:
# df['DIVIDED_SET']= df['DIVIDED_SET'].fillna((df['DIVIDED_SET'].mean()), inplace=True)
# df['SEX']= df['SEX'].fillna((df['SEX'].mean()), inplace=True)
# df['AGE']= df['AGE'].fillna((df['AGE'].mean()), inplace=True)
# df['RESI_COST']= df['RESI_COST'].fillna((df['RESI_COST'].mean()), inplace=True)
# df['RESI_TYPE_CODE']= df['RESI_TYPE_CODE'].fillna((df['RESI_TYPE_CODE'].mean()), inplace=True)
# df['FP_CAREER']= df['FP_CAREER'].fillna((df['FP_CAREER'].mean()), inplace=True)
# df['CUST_RGST']= df['CUST_RGST'].fillna((df['CUST_RGST'].mean()), inplace=True)
# df['TOTALPREM']= df['TOTALPREM'].fillna((df['TOTALPREM'].mean()), inplace=True)
# df['MINCRDT']= df['MINCRDT'].fillna((df['MINCRDT'].mean()), inplace=True)
# df['MAXCRDT']= df['MAXCRDT'].fillna((df['MAXCRDT'].mean()), inplace=True)
# df['CHLD_CNT']= df['CHLD_CNT'].fillna((df['CHLD_CNT'].mean()), inplace=True)
# df['LTBN_CHLD_AGE']= df['LTBN_CHLD_AGE'].fillna((df['LTBN_CHLD_AGE'].mean()), inplace=True)
# df['MAX_PAYM_YM']= df['MAX_PAYM_YM'].fillna((df['MAX_PAYM_YM'].mean()), inplace=True)
# df['MAX_PRM']= df['MAX_PRM'].fillna((df['MAX_PRM'].mean()), inplace=True)
# df['CUST_INCM']= df['CUST_INCM'].fillna((df['CUST_INCM'].mean()), inplace=True)
# df['RCBASE_HSHD_INCM']= df['RCBASE_HSHD_INCM'].fillna((df['RCBASE_HSHD_INCM'].mean()), inplace=True)
# df['JPBASE_HSHD_INCM']= df['JPBASE_HSHD_INCM'].fillna((df['JPBASE_HSHD_INCM'].mean()), inplace=True)

In [693]:
def variance(x):
    n = len(x)
    deviations = de_mean(x)
    return sum_of_squares(deviations) / (n - 1)

def standard_deviation(x):
    return math.sqrt(variance(x))

def de_mean(x):
    x_bar = mean(x)
    return [x_i - x_bar for x_i in x]

def sum_of_squares(v):
    return dot(v, v)

In [694]:
def correlation(x, y):
    stdev_x = standard_deviation(x)
    stdev_y = standard_deviation(y)
    if stdev_x > 0 and stdev_y > 0:
        return covariance(x, y) / stdev_x / stdev_y
    else:
        return 0 

    #4가지 선택

x_data = df_SEX
#x_data = df_AGE
#x_data = df_DIVIDED_SET
#x_data = df_RESI_COST
# x_data = df_JPBASE_HSHD_INCM
y_data = df['SIU_CUST_YN']
#correlation(x_data, y_data)직

In [695]:
#names = ["df_DIVIDED_SET", "df_SEX", "df_AGE", "df_RESI_COST", "df_RESI_TYPE_CODE", "df_FP_CAREER", "df_CUST_RGST", "df_CTPR", "df_OCCP_GRP_1", "df_OCCP_GRP_2", "df_TOTALPREM", "df_MINCRDT", "df_MAXCRDT", "df_WEDD_YN", "df_MATE_OCCP_GRP_1", "df_MATE_OCCP_GRP_2", "df_CHLD_CNT", "df_LTBN_CHLD_AGE", "df_MAX_PAYM_YM", "df_MAX_PRM", "df_CUST_INCM", "df_RCBASE_HSHD_INCM", "df_JPBASE_HSHD_INCM"]
#df[:5]
#df.dtypes

In [696]:
np.corrcoef(x_data, y_data)

array([[ 1.        ,  0.04650657],
       [ 0.04650657,  1.        ]])

In [697]:
df['AGE'] = df['AGE'].map(lambda x:0 if x < 11 else x)

In [698]:
df['AGE'] = df['AGE'].map(lambda x:10 if x >10 and x<21 else x)

In [699]:
df['AGE'] = df['AGE'].map(lambda x:20 if x >20 and x<31 else x)

In [700]:
df['AGE'] = df['AGE'].map(lambda x:30 if x >30 and x<41 else x)

In [701]:
df['AGE'] = df['AGE'].map(lambda x:40 if x >40 and x<51 else x)

In [702]:
df['AGE'] = df['AGE'].map(lambda x:50 if x >50 and x<61 else x)

In [703]:
df['AGE'] = df['AGE'].map(lambda x:60 if x >60 and x<71 else x)

In [704]:
df['AGE'] = df['AGE'].map(lambda x:70 if x >70 and x<81 else x)

In [705]:
df['AGE'] = df['AGE'].map(lambda x:80 if x >80  else x)

In [706]:
grouped = df['SIU_CUST_YN'].groupby(df['AGE'])
grouped.mean()

AGE
0     0.024490
10    0.022425
20    0.072894
30    0.090255
40    0.087609
50    0.120047
60    0.089448
70    0.035117
80    0.000000
Name: SIU_CUST_YN, dtype: float64

In [707]:
df['AGE'] = df['AGE'].map(lambda x:100 if x == 50 else x) 

In [708]:
df['AGE'] = df['AGE'].map(lambda x:70 if x == 30 or x == 40 or x == 60 else x) 

In [709]:
df['AGE'] = df['AGE'].map(lambda x:40 if x == 20 else x) 

In [710]:
df['AGE'] = df['AGE'].map(lambda x:0 if  x != 100 and x!=70 and x!=40  else x)

In [711]:
df["AGE"]

CUST_ID
1         70
2        100
3        100
4         70
5        100
6         70
7        100
8        100
9        100
12       100
13        70
15       100
16       100
17        70
18        70
19        70
20       100
21        70
22       100
23         0
24       100
25        70
26       100
27       100
28        70
29        70
30       100
31       100
32       100
33        70
        ... 
11063      0
8711      40
2058       0
1699       0
15499     40
6156      40
14826     40
12570     40
21572     40
18279     70
2409       0
14389     70
12858     70
10744      0
19371      0
19375      0
3561      70
19406     70
5926      40
721      100
19376      0
19838     40
21597     40
20276    100
2087       0
875       70
21483     40
21940     40
20356      0
17118      0
Name: AGE, dtype: int64

In [712]:
x_data = df_AGE
y_data = df['SIU_CUST_YN']

In [713]:
np.corrcoef(x_data, y_data)

array([[ 1.        ,  0.08830201],
       [ 0.08830201,  1.        ]])

In [714]:
df['RESI_COST'] = df['RESI_COST'].map(lambda x:5000 if x>=0 and x <10000 else x)

In [715]:
df['RESI_COST'] = df['RESI_COST'].map(lambda x:15000 if x>=10000 and x <20000 else x)

In [716]:
df['RESI_COST'] = df['RESI_COST'].map(lambda x:25000 if x>=20000 and x <30000 else x)

In [717]:
df['RESI_COST'] = df['RESI_COST'].map(lambda x:35000 if x>=30000 and x <40000 else x)

In [718]:
df['RESI_COST'] = df['RESI_COST'].map(lambda x:45000 if x>=40000 and x <50000 else x)

In [719]:
df['RESI_COST'] = df['RESI_COST'].map(lambda x:55000 if x>=50000 and x <60000 else x)

In [720]:
df['RESI_COST'] = df['RESI_COST'].map(lambda x:65000 if x>=60000 and x <70000 else x)

In [721]:
df['RESI_COST'] = df['RESI_COST'].map(lambda x:75000 if x>=70000 else x)

In [722]:
grouped = df['SIU_CUST_YN'].groupby(df['RESI_COST'])
grouped.mean()

RESI_COST
5000     0.101288
15000    0.089722
25000    0.070947
35000    0.059690
45000    0.054770
55000    0.057252
65000    0.071429
75000    0.042453
Name: SIU_CUST_YN, dtype: float64

In [723]:
df['RESI_COST'] = df['RESI_COST'].map(lambda x:80 if x == 5000 else x) 

In [724]:
df['RESI_COST'] = df['RESI_COST'].map(lambda x:50 if x == 15000 or x == 25000 or x==65000else x) 

In [725]:
df['RESI_COST'] = df['RESI_COST'].map(lambda x:10 if x == 35000 or x==45000or x == 55000 else x) 

In [726]:
df['RESI_COST'] = df['RESI_COST'].map(lambda x:0 if   x != 80 and x != 50 and x!=10 else x)

In [727]:
x_data = df_RESI_COST
y_data = df['SIU_CUST_YN']

In [728]:
np.corrcoef(x_data, y_data)

array([[ 1.        ,  0.04951917],
       [ 0.04951917,  1.        ]])

In [729]:
df['TOTALPREM'] = df['TOTALPREM'].map(lambda x:5 if x>=0 and x <50000000 else x)

In [730]:
df['TOTALPREM'] = df['TOTALPREM'].map(lambda x:10 if x>=50000000 and x <100000000 else x)

In [731]:
df['TOTALPREM'] = df['TOTALPREM'].map(lambda x:15if x>=100000000 and x <150000000 else x)

In [732]:
df['TOTALPREM'] = df['TOTALPREM'].map(lambda x:20 if x>=150000000 and x <200000000 else x)

In [733]:
df['TOTALPREM'] = df['TOTALPREM'].map(lambda x:25 if x>=200000000 else x)

In [734]:
grouped = df['SIU_CUST_YN'].groupby(df['TOTALPREM'])
grouped.mean()

TOTALPREM
5.0     0.085488
10.0    0.103960
15.0    0.109489
20.0    0.109677
25.0    0.089623
Name: SIU_CUST_YN, dtype: float64

In [735]:
df['TOTALPREM'] = df['TOTALPREM'].map(lambda x:50 if x == 10 or x == 15 or x == 20 else x) 

In [736]:
df['TOTALPREM'] = df['TOTALPREM'].map(lambda x:0 if   x != 50  else x) 

In [737]:
x_data = df_TOTALPREM
y_data = df['SIU_CUST_YN']

In [738]:
np.corrcoef(x_data, y_data)

array([[ 1.        ,  0.02162329],
       [ 0.02162329,  1.        ]])

In [739]:
grouped = df['SIU_CUST_YN'].groupby(df['MINCRDT'])
grouped.mean()

MINCRDT
0.000000     0.023256
1.000000     0.027778
2.000000     0.048998
3.000000     0.064151
4.000000     0.043796
5.000000     0.076763
5.850519     0.097650
6.000000     0.069316
7.000000     0.136364
8.000000     0.186154
9.000000     0.212121
10.000000    0.128205
28.000000    0.000000
99.000000    0.000000
Name: SIU_CUST_YN, dtype: float64

In [740]:
df['MINCRDT'] = df['MINCRDT'].map(lambda x:80 if x==9.000000else x)

In [741]:
df['MINCRDT'] = df['MINCRDT'].map(lambda x:50 if x==8.000000 or x==10.000000or x==7.000000else x)

In [742]:
df['MINCRDT'] = df['MINCRDT'].map(lambda x:30 if x==5.850519  else x)

In [743]:
df['MINCRDT'] = df['MINCRDT'].map(lambda x:0 if x!= 80 and x!=50 and x!= 30  else x)

In [744]:
x_data = df_MINCRDT
y_data = df['SIU_CUST_YN']

np.corrcoef(x_data, y_data)

array([[ 1.        ,  0.07940469],
       [ 0.07940469,  1.        ]])

In [745]:
grouped = df['SIU_CUST_YN'].groupby(df['MAXCRDT'])
grouped.mean()

MAXCRDT
0.000000     0.031250
1.000000     0.047619
2.000000     0.108696
3.000000     0.068182
4.000000     0.139535
5.000000     0.130435
6.000000     0.068221
7.000000     0.126374
8.000000     0.172967
9.000000     0.202532
10.000000    0.205882
19.529516    0.097650
28.000000    0.000000
99.000000    0.025489
Name: SIU_CUST_YN, dtype: float64

In [746]:
df['MAXCRDT']= df['MAXCRDT'].map(lambda x:80 if x==10.000000or x==9.000000else x)

In [747]:
df['MAXCRDT']= df['MAXCRDT'].map(lambda x:50 if x==8.000000or x==7.000000or x==2.000000 or x==4.000000 or x==5.000000else x)

In [748]:
df['MAXCRDT'] = df['MAXCRDT'].map(lambda x:0 if x!= 80 and x!=50  else x)

In [749]:
x_data = df_MAXCRDT
y_data = df['SIU_CUST_YN']

np.corrcoef(x_data, y_data)

array([[ 1.        ,  0.09121289],
       [ 0.09121289,  1.        ]])

In [750]:
df['LTBN_CHLD_AGE'] = df['LTBN_CHLD_AGE'].map(lambda x:0 if x < 5 else x)
df['LTBN_CHLD_AGE'] = df['LTBN_CHLD_AGE'].map(lambda x:5 if x >=5 and x<10 else x)
df['LTBN_CHLD_AGE'] = df['LTBN_CHLD_AGE'].map(lambda x:10 if x >=10 and x<15 else x)
df['LTBN_CHLD_AGE'] = df['LTBN_CHLD_AGE'].map(lambda x:15 if x >=15 and x<20 else x)
df['LTBN_CHLD_AGE'] = df['LTBN_CHLD_AGE'].map(lambda x:20 if x >=20 and x<25 else x)
df['LTBN_CHLD_AGE'] = df['LTBN_CHLD_AGE'].map(lambda x:25 if x >=25 and x<30 else x)
df['LTBN_CHLD_AGE'] = df['LTBN_CHLD_AGE'].map(lambda x:30 if x >=30 and x<36 else x)

In [751]:
grouped = df['SIU_CUST_YN'].groupby(df['LTBN_CHLD_AGE'])
grouped.mean()

LTBN_CHLD_AGE
0.0     0.078449
5.0     0.066061
10.0    0.091556
15.0    0.082712
20.0    0.108756
25.0    0.108234
30.0    0.134487
Name: SIU_CUST_YN, dtype: float64

In [752]:
df['LTBN_CHLD_AGE']= df['LTBN_CHLD_AGE'].map(lambda x:80 if x==20.0 or x==30.0 or x==25.0 else x)

In [753]:
df['LTBN_CHLD_AGE']= df['LTBN_CHLD_AGE'].map(lambda x:40 if x==10.0 or x==15.0 else x)

In [754]:
df['LTBN_CHLD_AGE'] = df['LTBN_CHLD_AGE'].map(lambda x:0 if x!=80 and x!=40 else x)

In [755]:
df['LTBN_CHLD_AGE'] 

CUST_ID
1        40.0
2        40.0
3         0.0
4         0.0
5        40.0
6        80.0
7        80.0
8        80.0
9        40.0
12       80.0
13        0.0
15        0.0
16        0.0
17        0.0
18        0.0
19       80.0
20       80.0
21       80.0
22       80.0
23        0.0
24       80.0
25       40.0
26       80.0
27       80.0
28       80.0
29       40.0
30        0.0
31       80.0
32       80.0
33       80.0
         ... 
11063     0.0
8711      0.0
2058      0.0
1699      0.0
15499     0.0
6156      0.0
14826     0.0
12570     0.0
21572     0.0
18279    80.0
2409      0.0
14389     0.0
12858     0.0
10744     0.0
19371     0.0
19375     0.0
3561      0.0
19406     0.0
5926      0.0
721      80.0
19376     0.0
19838     0.0
21597     0.0
20276    80.0
2087      0.0
875      40.0
21483     0.0
21940     0.0
20356     0.0
17118     0.0
Name: LTBN_CHLD_AGE, dtype: float64

In [756]:
x_data = df_LTBN_CHLD_AGE
y_data = df['SIU_CUST_YN']

np.corrcoef(x_data, y_data)

array([[ 1.       ,  0.0562341],
       [ 0.0562341,  1.       ]])

In [757]:
df['CTPR'] = df['CTPR'].astype("category")
df['OCCP_GRP_1'] = df['OCCP_GRP_1'].astype("category")
df['OCCP_GRP_2'] = df['OCCP_GRP_2'].astype("category")
df['MATE_OCCP_GRP_1'] = df['MATE_OCCP_GRP_1'].astype("category")
df['MATE_OCCP_GRP_2'] = df['MATE_OCCP_GRP_2'].astype("category")

df.dtypes

DIVIDED_SET            int64
SIU_CUST_YN            int64
SEX                    int64
AGE                    int64
RESI_COST              int64
RESI_TYPE_CODE       float64
FP_CAREER              int64
CUST_RGST            float64
CTPR                category
OCCP_GRP_1          category
OCCP_GRP_2          category
TOTALPREM            float64
MINCRDT              float64
MAXCRDT              float64
WEDD_YN                int64
MATE_OCCP_GRP_1     category
MATE_OCCP_GRP_2     category
CHLD_CNT             float64
LTBN_CHLD_AGE        float64
MAX_PAYM_YM          float64
MAX_PRM              float64
CUST_INCM            float64
RCBASE_HSHD_INCM       int64
JPBASE_HSHD_INCM     float64
dtype: object

In [758]:
# df1 = pd.get_dummies(df, columns=["CTPR","OCCP_GRP_1","OCCP_GRP_2","MATE_OCCP_GRP_1","MATE_OCCP_GRP_2"], drop_first = True)
# df1.describe()
# df1.head()

In [759]:
df.columns

Index(['DIVIDED_SET', 'SIU_CUST_YN', 'SEX', 'AGE', 'RESI_COST',
       'RESI_TYPE_CODE', 'FP_CAREER', 'CUST_RGST', 'CTPR', 'OCCP_GRP_1',
       'OCCP_GRP_2', 'TOTALPREM', 'MINCRDT', 'MAXCRDT', 'WEDD_YN',
       'MATE_OCCP_GRP_1', 'MATE_OCCP_GRP_2', 'CHLD_CNT', 'LTBN_CHLD_AGE',
       'MAX_PAYM_YM', 'MAX_PRM', 'CUST_INCM', 'RCBASE_HSHD_INCM',
       'JPBASE_HSHD_INCM'],
      dtype='object')

In [760]:
grouped = df['SIU_CUST_YN'].groupby(df['CTPR'])
#print(grouped.describe())
grouped.mean()

CTPR
강원    0.141221
경기    0.072437
경남    0.064295
경북    0.050223
광주    0.195734
대구    0.061606
대전    0.085837
부산    0.142446
서울    0.090292
세종    0.054054
울산    0.029457
인천    0.135682
전남    0.098456
전북    0.114350
제주    0.000000
충남    0.056277
충북    0.026316
Name: SIU_CUST_YN, dtype: float64

In [761]:
df['CTPR'] = df['CTPR'].map(lambda x:50 if x == '강원' or x == '광주' or x == '부산' or x == '인천' or x == '전북' else x) 

In [762]:
df['CTPR'] = df['CTPR'].map(lambda x:30 if x == '경기' or x=='경남' or x=='경북'  or x=='대구'or x=='대전' or x=='서울' or x=='전남' else x)

In [763]:
df['CTPR'] = df['CTPR'].map(lambda x:0 if  x != 30 and x!=50  else x)

In [764]:
df['CTPR']

CUST_ID
1         0
2        30
3        30
4        30
5        50
6         0
7        30
8        30
9        30
12       30
13       30
15       30
16       50
17       30
18       30
19       30
20       30
21       30
22       30
23       30
24       50
25       30
26       50
27       30
28       50
29        0
30       30
31       50
32       30
33       30
         ..
11063    50
8711     30
2058     30
1699     30
15499    50
6156     30
14826    30
12570    30
21572    30
18279    50
2409     30
14389    30
12858    30
10744    50
19371    50
19375    30
3561     50
19406    50
5926     30
721      30
19376    30
19838    30
21597    30
20276    50
2087     30
875      30
21483    30
21940    30
20356    30
17118    30
Name: CTPR, dtype: int64

In [765]:
x_data = df['CTPR']
y_data = df['SIU_CUST_YN']


np.corrcoef(x_data, y_data)

array([[ 1.        ,  0.11247773],
       [ 0.11247773,  1.        ]])

In [766]:
grouped = df['SIU_CUST_YN'].groupby(df['OCCP_GRP_1'])
#print(grouped.describe())
grouped.mean()

OCCP_GRP_1
1.주부      0.113130
2.자영업     0.142722
3.사무직     0.083712
4.전문직     0.053650
5.서비스     0.102534
6.제조업     0.042587
7.1차산업    0.038462
8.기타      0.063802
Name: SIU_CUST_YN, dtype: float64

In [767]:
df['OCCP_GRP_1'] = df['OCCP_GRP_1'].map(lambda x:50 if x == '1.주부' or x == '5.서비스' or x == '2.자영업'else x) 

In [768]:
df['OCCP_GRP_1'] = df['OCCP_GRP_1'].map(lambda x:30 if x == '3.사무직' or x=='8.기타'else x)

In [769]:
df['OCCP_GRP_1'] = df['OCCP_GRP_1'].map(lambda x:15 if x == '4.전문직' or x=='6.제조업' or x=='7.1차산업'else x)

In [770]:
df['OCCP_GRP_1'] = df['OCCP_GRP_1'].map(lambda x:0 if  x != 15 and x != 30 and x!=50  else x)

In [771]:
df['OCCP_GRP_1']

CUST_ID
1        30
2        30
3        50
4        50
5        50
6        30
7        50
8        50
9        15
12       15
13       15
15       30
16       50
17       50
18       50
19       50
20       50
21       50
22       50
23       50
24       50
25       50
26       50
27       15
28       30
29       30
30       50
31       50
32       50
33       30
         ..
11063    30
8711     30
2058     30
1699     30
15499    30
6156     30
14826    30
12570    30
21572    30
18279    30
2409     30
14389    15
12858    30
10744    30
19371    30
19375    30
3561     15
19406    50
5926     30
721      50
19376    30
19838    30
21597    30
20276    50
2087     30
875      50
21483    50
21940    30
20356    30
17118    30
Name: OCCP_GRP_1, dtype: int64

In [772]:
x_data = df['OCCP_GRP_1']
y_data = df['SIU_CUST_YN']


np.corrcoef(x_data, y_data)

array([[ 1.        ,  0.09579155],
       [ 0.09579155,  1.        ]])

In [773]:
grouped = df['SIU_CUST_YN'].groupby(df['OCCP_GRP_2'])
#print(grouped.describe())
grouped.mean()

OCCP_GRP_2
1차산업 종사자    0.047354
2차산업 종사자    0.044816
3차산업 종사자    0.134755
고소득 전문직     0.000000
고소득의료직      0.057143
고위 공무원      0.023810
공무원         0.054054
교사          0.024691
교육관련직       0.066838
기업/단체 임원    0.084746
기타          0.063232
단순 노무직      0.095238
단순 사무직      0.096346
대학교수/강사     0.066667
법무직 종사자     0.000000
사무직         0.085444
예체능계 종사자    0.105590
운전직         0.065306
의료직 종사자     0.055215
자영업         0.133684
전문직         0.055072
종교인/역술인     0.151515
주부          0.113250
학생          0.059934
학자/연구직      0.025641
Name: SIU_CUST_YN, dtype: float64

In [774]:
df['OCCP_GRP_2'] = df['OCCP_GRP_2'].map(lambda x:50 if  x == '3차산업 종사자' or x=='자영업'or x == '주부' or x == '예체능계 종사자' else x)

In [775]:
df['OCCP_GRP_2'] = df['OCCP_GRP_2'].map(lambda x:30 if  x == '단순 노무직' or x=='단순 사무직'or x == '사무직' or x == '기업/단체 임원' else x)

In [776]:
df['OCCP_GRP_2'] = df['OCCP_GRP_2'].map(lambda x:15 if  x == '교육관련직' or x=='기타' or x=='대학교수/강사'or x=='운전직'or x=='기타'or x=='공무원' or x=='고소득의료직'or x=='전문직' or x=='학생 'else x)

In [777]:
df['OCCP_GRP_2'] = df['OCCP_GRP_2'].map(lambda x:0 if  x != 15 and x != 30 and x!=50  else x)

In [778]:
df['OCCP_GRP_2']

CUST_ID
1        30
2        30
3         0
4        50
5        50
6         0
7        50
8        50
9        15
12       15
13       15
15       30
16       50
17        0
18        0
19       50
20       50
21       50
22       50
23       50
24       50
25       50
26       50
27       15
28       30
29       15
30       50
31       50
32       50
33       30
         ..
11063     0
8711      0
2058      0
1699      0
15499     0
6156      0
14826     0
12570     0
21572     0
18279    30
2409      0
14389     0
12858    30
10744     0
19371     0
19375     0
3561      0
19406    50
5926      0
721      50
19376     0
19838     0
21597     0
20276    50
2087      0
875      50
21483    50
21940     0
20356     0
17118     0
Name: OCCP_GRP_2, dtype: int64

In [779]:
x_data = df['OCCP_GRP_2']
y_data = df['SIU_CUST_YN']


np.corrcoef(x_data, y_data)

array([[ 1.        ,  0.10778524],
       [ 0.10778524,  1.        ]])

In [780]:
grouped = df['SIU_CUST_YN'].groupby(df['MATE_OCCP_GRP_1'])
#print(grouped.describe())
grouped.mean()

MATE_OCCP_GRP_1
1.주부      0.073990
2.자영업     0.123351
3.사무직     0.092691
4.전문직     0.073887
5.서비스     0.102113
6.제조업     0.089251
7.1차산업    0.089457
8.기타      0.089810
Name: SIU_CUST_YN, dtype: float64

In [781]:
df['MATE_OCCP_GRP_1'] = df['MATE_OCCP_GRP_1'].map(lambda x:50 if  x == '2.자영업' or x=='5.서비스' else x)

In [782]:
df['MATE_OCCP_GRP_1'] = df['MATE_OCCP_GRP_1'].map(lambda x:30 if  x == '3.사무직' or x=='6.제조업'or x=='7.1차산업'or x=='8.기타' else x)

In [783]:
df['MATE_OCCP_GRP_1'] = df['MATE_OCCP_GRP_1'].map(lambda x:15 if  x == '1.주부' or x=='4.전문직' else x)

In [784]:
df['MATE_OCCP_GRP_1'] = df['MATE_OCCP_GRP_1'].map(lambda x:0 if  x != 15 and x != 30 and x!=50  else x)

In [785]:
df['MATE_OCCP_GRP_1']

CUST_ID
1        30
2        15
3        30
4        30
5        30
6        15
7        30
8        50
9        15
12       15
13       50
15       15
16       30
17       15
18       30
19       15
20       50
21       30
22       50
23       50
24       30
25       50
26       50
27       15
28       50
29       50
30       30
31       30
32       50
33       50
         ..
11063    30
8711     30
2058     30
1699     30
15499    30
6156     30
14826    30
12570    30
21572    30
18279    15
2409     30
14389    30
12858    30
10744    30
19371    30
19375    30
3561     30
19406    30
5926     30
721      15
19376    30
19838    30
21597    30
20276    15
2087     30
875      30
21483    30
21940    30
20356    30
17118    30
Name: MATE_OCCP_GRP_1, dtype: int64

In [786]:
x_data = df['MATE_OCCP_GRP_1']
y_data = df['SIU_CUST_YN']


np.corrcoef(x_data, y_data)

array([[ 1.        ,  0.03648088],
       [ 0.03648088,  1.        ]])

In [787]:
grouped = df['SIU_CUST_YN'].groupby(df['MATE_OCCP_GRP_2'])
#print(grouped.describe())
grouped.mean()

MATE_OCCP_GRP_2
1차산업 종사자    0.086835
2차산업 종사자    0.095273
3차산업 종사자    0.083237
고소득 전문직     0.000000
고소득의료직      0.034483
고위 공무원      0.054054
공무원         0.043860
교사          0.049180
교육관련직       0.075472
기업/단체 임원    0.138211
기타          0.108597
단순 노무직      0.054795
단순 사무직      0.060000
대학교수/강사     0.000000
사무직         0.099607
예체능계 종사자    0.045455
운전직         0.096654
의료직 종사자     0.063158
자영업         0.126351
전문직         0.097959
종교인/역술인     0.214286
주부          0.074208
학생          0.233333
학자/연구직      0.095238
Name: SIU_CUST_YN, dtype: float64

In [788]:
df['MATE_OCCP_GRP_2'] = df['MATE_OCCP_GRP_2'].map(lambda x:80 if x == '종교인/역술인' or x=='학생'  else x)

In [789]:
df['MATE_OCCP_GRP_2'] = df['MATE_OCCP_GRP_2'].map(lambda x:50 if x == '기업/단체 임원' or x=='기타' or x =='자영업'  else x)

In [790]:
df['MATE_OCCP_GRP_2'] = df['MATE_OCCP_GRP_2'].map(lambda x:30 if  x == '1차산업 종사자' or x=='3차산업 종사자'or x == '2차산업 종사자' or x == '사무직' or x == '운전직'or x == '전문직'or x == '학자/연구직'else x)

In [791]:
df['MATE_OCCP_GRP_2'] = df['MATE_OCCP_GRP_2'].map(lambda x:15 if  x == '고위 공무원' or x=='공무원'or x == '교사' or x == '단순 노무직' or x == '단순 사무직' or x == '의료직 종사자' or x == '주부'or x == '교육관련직' or x == '교육관련직'else x)

In [792]:
df['MATE_OCCP_GRP_2'] = df['MATE_OCCP_GRP_2'].map(lambda x:0 if  x != 15 and x != 30 and x!=50 and x!=80 else x)

In [793]:
df['MATE_OCCP_GRP_2']

CUST_ID
1        30
2        15
3        30
4        30
5        15
6        15
7        30
8        30
9        15
12       15
13        0
15       15
16       30
17       15
18       15
19       15
20       30
21       30
22       50
23       30
24       30
25        0
26       50
27       15
28       30
29       30
30       30
31       30
32       30
33       50
         ..
11063    30
8711     30
2058     30
1699     30
15499    30
6156     30
14826    30
12570    30
21572    30
18279    15
2409     30
14389    30
12858    30
10744    30
19371    30
19375    30
3561     30
19406    30
5926     30
721      15
19376    30
19838    30
21597    30
20276    15
2087     30
875      30
21483    30
21940    30
20356    30
17118    30
Name: MATE_OCCP_GRP_2, dtype: int64

In [794]:
x_data = df['MATE_OCCP_GRP_2']
y_data = df['SIU_CUST_YN']


np.corrcoef(x_data, y_data)

array([[ 1.        ,  0.05235873],
       [ 0.05235873,  1.        ]])